/** Bancos con presencia en el norte de La Pampa y ~600 km a la redonda. */
export const BANCOS_EMISORES_AR: readonly string[] = [
  'Banco de La Pampa',
  'Banco de la Nación Argentina',
  'Banco de la Provincia de Buenos Aires',
  'Banco de Córdoba',
  'Banco de San Luis',
  'Banco Galicia',
  'Banco Santander Argentina',
  'BBVA Argentina',
  'Banco Macro',
  'Banco Credicoop',
  'Banco Patagonia',
  'Banco Supervielle',
  'Banco Hipotecario',
  'HSBC Bank Argentina',
  'ICBC Argentina',
  'Banco Comafi',
  'Banco Industrial (Bind)',
  'Banco de la Ciudad de Buenos Aires',
  'Banco Provincia de Neuquén',
  'Banco Santa Fe',
  'Banco de Mendoza',
  'Banco del Sol',
];
